<template>
    <div>
        <header>
            <h1>Header</h1>
        </header>
        <router-view></router-view>
        <footer>
            <h1>Footer</h1>
        </footer>
    </div>
</template>
